# Base uCore HCI Ansible Playbook
---
- name: The uCore basic configuration HCI Ansible Playbook
  hosts: ucorepro
  become: true

  tasks:
    - name: Configure hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Configure timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Copy sshd_config
      ansible.builtin.copy:
        src: files/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted

    - name: Setup network card script
      ansible.builtin.copy:
        src: files/scripts/network-card.sh
        dest: /usr/local/bin/network-card.sh
        mode: '0755'
        owner: root
        group: root

    - name: Setup systemd service
      ansible.builtin.copy:
        src: files/miscellaneous/network-card.service
        dest: /etc/systemd/system/network-card.service
        mode: '0644'
        owner: root
        group: root

    - name: Enable and start the service
      ansible.builtin.systemd:
        name: network-card
        enabled: true
        daemon_reload: true
        state: restarted

    - name: Setup boot notification script
      ansible.builtin.import_tasks:
        file: tasks/boot-notify.ansible.yml

    - name: Setup disk monitoring script
      ansible.builtin.import_tasks:
        file: tasks/disk-monitoring.ansible.yml

    - name: Setup file deduplication script
      ansible.builtin.import_tasks:
        file: tasks/deduplication.ansible.yml

    - name: Setup podman auto-update
      ansible.builtin.systemd:
        name: podman-auto-update.timer
        enabled: true
        state: started

    - name: Setup blocky quadlet
      ansible.builtin.import_tasks:
        file: tasks/blocky.ansible.yml
      vars:
        blocky_config_dir: /var/mnt/disk/shared/containers/blocky

    - name: Setup caddy quadlet
      ansible.builtin.import_tasks:
        file: tasks/caddy.ansible.yml
      vars:
        caddy_config_dir: /var/mnt/disk/shared/containers/caddy
        caddyfile_name: ucorepro

    - name: Setup restic nextcloud backup
      ansible.builtin.import_tasks:
        file: tasks/restic.ansible.yml
      vars:
        restic_dir: /var/mnt/disk/shared/containers
        restic_config: nextcloud
        restic_backup_path: "/host/mnt/disk/shared/containers/nextcloud"
        restic_exclude_path:

    - name: Setup restic for containers
      ansible.builtin.import_tasks:
        file: tasks/restic.ansible.yml
      vars:
        restic_dir: /var/mnt/disk/shared/containers
        restic_config: "{{ inventory_hostname }}"
        restic_backup_path: "/host/mnt/disk/shared/containers"
        restic_exclude_path: "/host/mnt/disk/shared/containers/nextcloud"

    - name: Setup wireguard VPN
      ansible.builtin.import_tasks:
        file: tasks/wireguard.ansible.yml
      vars:
        wg_conf_name: ucorepro
        wg_conf_port: 55820

    - name: Enable linger for core user
      ansible.builtin.file:
        path: /var/lib/systemd/linger/core
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Allow DLNA on firewalld
      ansible.posix.firewalld:
        port: 1900/udp
        permanent: true
        state: enabled
        immediate: true
