# Base uCore HCI Ansible Playbook
---
- name: The uCore basic configuration HCI Ansible Playbook
  hosts: ucorepro
  become: true
  tasks:
    - name: Configure hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Configure timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Setup network card script
      ansible.builtin.copy:
        src: files/scripts/network-card.sh
        dest: /usr/local/bin/network-card.sh
        mode: '0755'
        owner: root
        group: root

    - name: Setup systemd service
      ansible.builtin.copy:
        src: files/miscellaneous/network-card.service
        dest: /etc/systemd/system/network-card.service
        mode: '0644'
        owner: root
        group: root

    - name: Enable and start the service
      ansible.builtin.systemd:
        name: network-card
        enabled: true
        daemon_reload: true
        state: restarted
