# Network VM setup playbook
# - Essential configuration
# - DNS server
# - NAT server
# - Web server
# - Wireguard VPN
# Required VM:
# - 1 core, 1GB RAM, 8GB disk
# - 2 network interfaces 10.0.0.199/24, 10.0.1.254/24
---
- name: Setup network VM
  hosts: vm-network
  become: true

  tasks:
    - name: Setup debian essential configuration
      ansible.builtin.import_tasks:
        file: tasks/debian-essential.ansible.yml

    - name: Setup DNS server
      ansible.builtin.import_tasks:
        file: tasks/dns.ansible.yml

    - name: Setup wireguard VPN
      ansible.builtin.import_tasks:
        file: tasks/wireguard.ansible.yml

    - name: Setup firewall configuration with nat
      ansible.builtin.import_tasks:
        file: tasks/nftables.ansible.yml

    - name: Copy complejo.club cert
      ansible.builtin.copy:
        src: files/caddy/complejo.club.cert.pem
        dest: /etc/ssl/certs/complejo.club.cert.pem
        mode: '0600'
        user: caddy
        group: caddy
        decrypt: true

    - name: Copy complejo.club key
      ansible.builtin.copy:
        src: files/caddy/complejo.club.key.pem
        dest: /etc/ssl/certs/complejo.club.key.pem
        mode: '0600'
        user: caddy
        group: caddy
        decrypt: true

    - name: Setup web server
      ansible.builtin.import_tasks:
        file: tasks/caddy.ansible.yml
