# Master node setup playbook
# - Essential configuration
# Required VM:
# - 4 core, 8GB RAM, 48GB disk
# - 1 network interface 10.0.1.100/24
---
- name: Setup master node
  hosts: masterN
  become: true

  tasks:
    - name: Setup debian essential configuration
      ansible.builtin.import_tasks:
        file: tasks/debian-essential.ansible.yml

    - name: Setup kubernetes master
      ansible.builtin.import_tasks:
        file: tasks/master-k3s.ansible.yml
