# Worker node setup playbook
# - Essential configuration
# Required VM:
# - 4 core, 8GB RAM, 32GB disk
# - 1 network interface 10.0.1.10*/24
---
- name: Setup master node
  hosts: workerN
  become: true

  tasks:
    - name: Setup debian essential configuration
      ansible.builtin.import_tasks:
        file: tasks/debian-essential.ansible.yml

    - name: Setup kubernetes worker
      ansible.builtin.import_tasks:
        file: tasks/worker-k3s.ansible.yml
