# Raspberry-pi setup playbook
# - Essential configuration
# - Boot notification
# - Wireguard VPN
# - Firewall setup
# - NFS server
# - DNS server
# - Rclone sync
# - Ghorg git backup
# - Restic backup
# - Restic rest server
# - FreeDNS update
---
- name: Setup raspberry-pi
  hosts: rpi
  become: true

  tasks:
    - name: Setup debian essential configuration
      ansible.builtin.import_tasks:
        file: tasks/debian-essential.ansible.yml

    - name: Setup boot notification
      ansible.builtin.import_tasks:
        file: tasks/boot-notify.ansible.yml

    - name: Setup wireguard VPN
      ansible.builtin.import_tasks:
        file: tasks/wireguard.ansible.yml

    - name: Setup firewall
      ansible.builtin.import_tasks:
        file: tasks/nftables.ansible.yml

    - name: Setup disk monitoring
      ansible.builtin.import_tasks:
        file: tasks/disk-monitoring.ansible.yml

    - name: Setup DNS server
      ansible.builtin.import_tasks:
        file: tasks/dns.ansible.yml

    - name: Setup ghorg git backup
      ansible.builtin.import_tasks:
        file: tasks/ghorg.ansible.yml

    - name: Setup restic backup
      ansible.builtin.import_tasks:
        file: tasks/restic.ansible.yml

    - name: Setup restic rest-server
      ansible.builtin.import_tasks:
        file: tasks/restic-server.ansible.yml

    - name: Setup FreeDNS update
      ansible.builtin.import_tasks:
        file: tasks/freedns.ansible.yml
