# Description: Ansible playbook to setup remote containers for vps
---
- name: Containers setup for remote vps
  hosts: vps

  vars:
    invidious_data_dir: /srv/containers/invidious
    overleaf_data_dir: /srv/containers/overleaf
    scholarships_data_dir: /srv/containers/scholarships-db
    uptime_data_dir: /srv/containers/uptime-kuma

  tasks:
    - name: Enable podman auto-update
      ansible.builtin.systemd:
        name: podman-auto-update.timer
        scope: user
        enabled: true
        state: started

    - name: Create the home containers directory
      ansible.builtin.file:
        path: /home/core/.config/containers/systemd/
        state: directory
        owner: core
        group: core
        mode: "0755"

    - name: Copy all the quadlet files
      ansible.builtin.template:
        src: "files/containers/{{ item }}.j2"
        dest: "/home/core/.config/containers/systemd/{{ item }}"
        owner: core
        group: core
        mode: "0644"
      with_items:
        - "invidious.pod"
        - "invidious-db.container"
        - "invidious-app.container"
        - "invidious-helper.container"
        - "overleaf.pod"
        - "overleaf-db.container"
        - "overleaf-cache.container"
        - "overleaf-app.container"
        - "redlib.container"
        - "scholarships.pod"
        - "scholarships-app.container"
        - "scholarships-db.container"
        - "stirling.container"
        - "uptime.container"

    - name: Create the systemd user directory
      ansible.builtin.file:
        path: /home/core/.config/systemd/user/
        state: directory
        owner: core
        group: core
        mode: "0755"

    - name: Start systemd containers
      ansible.builtin.systemd:
        name: "{{ item }}"
        scope: user
        state: started
        daemon_reload: true
      with_items:
        - "invidious-pod.service"
        - "overleaf-pod.service"
        - "redlib.service"
        - "scholarships-pod.service"
        - "stirling.service"
        - "uptime.service"
