# VPS setup playbook
# - Essential configuration
# - Wireguard VPN
# - Web server
# - Uptime-kuma podman
# - Restic backup
# Required VM:
# - 1 core, 1GB RAM, 32GB disk
# - 1 network interface with public IP
---
- name: Setup network VM
  hosts: vps
  become: true

  tasks:
    - name: Configure hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Configure timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Copy sshd_config
      ansible.builtin.copy:
        src: files/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted

    - name: Setup wireguard VPN
      ansible.builtin.import_tasks:
        file: tasks/wireguard.ansible.yml
      vars:
        wg_conf_name: vps
        wg_conf_port: 55820

    - name: Setup podman auto-update
      ansible.builtin.systemd:
        name: podman-auto-update

    - name: Setup caddy quadlet
      ansible.builtin.import_tasks:
        file: tasks/caddy.ansible.yml
      vars:
        caddy_config_dir: /srv/containers/caddy
        caddyfile_name: vps

    - name: Setup restic for containers
      ansible.builtin.import_tasks:
        file: tasks/restic.ansible.yml
      vars:
        restic_dir: /srv/containers/restic
        restic_config: "{{ inventory_hostname }}"
        restic_backup_path: "/host/srv/containers"
        restic_exclude_path:

    - name: Enable linger for core user
      ansible.builtin.file:
        path: /var/lib/systemd/linger/core
        state: touch
        owner: root
        group: root
        mode: '0644'
