# Description: Configure caddy web server container
---
- name: Copy Caddy container quadlet
  ansible.builtin.copy:
    src: files/caddy/caddy.container
    dest: /etc/containers/systemd/caddy.container
    owner: root
    group: root
    mode: '0644'

- name: Create volume directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/mnt/disk/shared/containers/caddy/conf
    - /var/mnt/disk/shared/containers/caddy/data

- name: Copy Caddy configuration
  ansible.builtin.copy:
    src: files/caddy/{{ inventory_hostname }}.caddyfile
    dest: /var/mnt/disk/shared/containers/caddy/conf/Caddyfile
    owner: root
    group: root
    mode: '0644'

- name: Allow http/https ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - https
    - http

- name: Restart and enable Caddy container service
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    enabled: true
