# Description: Install ghorg git backup tool
---
- name: Download ghorg binary
  ansible.builtin.get_url:
    url: https://github.com/gabrie30/ghorg/releases/download/v1.9.12/ghorg_1.9.12_Linux_arm64.tar.gz
    dest: /tmp/ghorg.tar.gz
    mode: '0644'

- name: Create ghorg directory
  ansible.builtin.file:
    path: /tmp/ghorg
    state: directory
    mode: '0755'

- name: Extract ghorg binary
  ansible.builtin.unarchive:
    src: /tmp/ghorg.tar.gz
    dest: /tmp/ghorg
    remote_src: true
    creates: /tmp/ghorg/ghorg

- name: Move ghorg binary
  ansible.builtin.command:
    cmd: mv /tmp/ghorg/ghorg /usr/local/bin/ghorg
    creates: /usr/local/bin/ghorg

- name: Delete ghorg files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/ghorg
    - /tmp/ghorg.tar.gz

- name: Copy ghorg script
  ansible.builtin.copy:
    src: files/ghorg/{{ inventory_hostname }}.script-ghorg
    dest: /usr/local/bin/script-ghorg
    owner: root
    group: root
    mode: '0755'

- name: Copy ghorg systemd service
  ansible.builtin.copy:
    src: files/ghorg/ghorg.service
    dest: /etc/systemd/system/ghorg.service
    owner: root
    group: root
    mode: '0644'

- name: Copy ghorg systemd timer
  ansible.builtin.copy:
    src: files/ghorg/ghorg.timer
    dest: /etc/systemd/system/ghorg.timer
    owner: root
    group: root
    mode: '0644'

- name: Enable and start ghorg timer
  ansible.builtin.systemd:
    name: ghorg.timer
    enabled: true
    state: restarted
    daemon_reload: true
