# Description: Install and configure NFS server
---
- name: Install nfs packages
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Copy NFS exports configuration
  ansible.builtin.copy:
    src: files/nfs/{{ inventory_hostname }}.exports
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

- name: Restart NFS server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted
    enabled: true
