# Description: Setup Uptime-kuma with podman
---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - podman
    state: present

- name: Create uptime-kuma data path
  ansible.builtin.file:
    path: /var/lib/uptime-kuma
    state: directory
    mode: '0755'

- name: Create uptime-kuma podman container
  containers.podman.podman_container:
    name: uptime-kuma
    image: "docker.io/louislam/uptime-kuma:1"
    rm: true
    network: host
    volume:
      - /var/lib/uptime-kuma:/app/data
    label: "io.containers.autoupdate=registry"
    state: started

- name: Setup systemd service for uptime-kuma
  containers.podman.podman_generate_systemd:
    name: uptime-kuma
    new: true
    no_header: true
    dest: /etc/systemd/system

- name: Start and enable uptime-kuma service
  ansible.builtin.systemd:
    name: container-uptime-kuma
    daemon_reload: true
    enabled: true
    state: started

- name: Start and enable podman auto-update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    daemon_reload: true
    enabled: true
    state: started
