# Description: Setup wireguard VPN on the server
---
- name: Copy wireguard configuration
  ansible.builtin.copy:
    src: files/wireguard/wg-{{ wg_conf_name }}.conf
    dest: /etc/wireguard/wg-{{ wg_conf_name }}.conf
    mode: '0600'
    decrypt: true

- name: Allow forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: Allow masquerading
  ansible.posix.firewalld:
    masquerade: true
    permanent: true
    state: enabled
    immediate: true

- name: Allow wireguard port
  ansible.posix.firewalld:
    port: "{{ wg_conf_port }}/udp"
    permanent: true
    state: enabled
    immediate: true

- name: Enable and start wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg-{{ wg_conf_name }}
    enabled: true
    state: restarted
