# Description: Install k3s on the worker node
---
- name: Set kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  with_items:
    - { name: vm.panic_on_oom, value: 0 }
    - { name: vm.overcommit_memory, value: 1 }
    - { name: kernel.panic, value: 10 }
    - { name: kernel.panic_on_oops, value: 1 }

- name: Install k3s
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -sfL https://get.k3s.io | K3S_URL={{ K3S_URL }} K3S_TOKEN={{ K3S_TOKEN }} sh -
    executable: /bin/bash
    creates: /usr/local/bin/k3s
  register: k3s_install
  failed_when: k3s_install.rc != 0
